### ISSUE TITLE
Make `-t` control the global upper limit of export threads

### ISSUE THREAD

**Issue by kennytm** [pingcap/dumpling#105]
Separated from #76.

Currently, `-t` controls how many tables can be exported concurrently. If user provides `-r` in parameter, each table could be separated into some concurrent export jobs. So the `-t` doesn't mean exactly the upper limit of export threads.

We want to change `-t` to control the global upper limit of export threads, or provides another parameter to limit the concurrency of single table export, then the global concurrency can be controlled.

**Comment by lichunzhu** [comment]
Currently, `-t` can control the global concurrently dumpling tables.
