### ISSUE TITLE
dumpling costs too much time on getting schemas' tables

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#109]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Run dumpling with `-T` args to dump only one table. The TiDB cluster has more than 1000 schemas and 100000 tables. Each `select` query will cost about 3s.

2. What did you expect to see?

Dumpling data quickly and successfully.

3. What did you see instead?

Dumpling is blocked at [listAllTables](https://github.com/pingcap/dumpling/blob/master/v4/export/prepare.go#L78).

**Comment by lichunzhu** [comment]
The logic to get tables names in dumpling is:
1. Get all database names;
2. For all database names, execute `SELECT table_name FROM information_schema.tables WHERE table_schema = xxx and table_type ='BASE TABLE';` to get table names

In the above case, each `SELECT information_schema.tables` command takes 3-5 s, and there is a 1.5k schemas in the upstream cluster. Therefore, in the above process, dumpling will take 1.5h to get all table names.

**Comment by kennytm** [comment]
100,000 tables is the total count (1000 schemas × 100 tables/schema)?

**Comment by lichunzhu** [comment]
I think we can solve this problem by either of following solutions:

1. select all tables' info in one time and deal with them in dumpling.
2. use table filter `MatchSchema` to check whether this database's tables will be dumped. If not, don't check run query to check this schema's tables. This method can cover situations that users only dumps few table. But if they dump all the databases dumpling may fail to work again.

**Comment by kennytm** [comment]
we should definitely not perform the SELECT 1000 times, but please clarify whether it is 1000 × 100 tables or 1000 × 100000 tables.

**Comment by lichunzhu** [comment]
> 1000

Yes. Total count of tables of all schemas is 100,000. Total count of schemas is around 1500. The numbers of tables for per schema are not even. Besides, dumpling will be able to process if we specify `-B` argument.

**Comment by kennytm** [comment]
then reading the entire `select * from information_schema.schemata;` and `select * from information_schema.tables;` into memory should be fine.

**Comment by leoppro** [comment]
> we should definitely not perform the SELECT 1000 times, but please clarify whether it is 1000 × 100 tables or 1000 × 100000 tables.

the number of table is 1000(schema) * 100(table),
yes, dumpling `SELECT` 1000 times in currently implement.
