### ISSUE TITLE
Support specifying output file format

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#114]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some users need to specify filename format to avoid duplication.

**Describe the feature you'd like:**

Support specifying output file name format instead of formatted file name.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
Please clarify how the duplication could happen

**Comment by lichunzhu** [comment]
> Please clarify how the duplication could happen, as we have the `-o` parameter to define the output directory.

I suppose in the following situations users will use same `-o` index.

1. Some users want to dump part of the data from one table.
2. Some users may use serveral times of `--sql` which may cause this.

**Comment by kennytm** [comment]
For 2 if they forget to change `-o`, they may also forget to change the "file name".

For 1, the "part of data" may still produce multiple files.
