### ISSUE TITLE
Support `--tidb-force-priority` in dumpling like mydumper

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#115]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some users don't want dumpling to affect their normal TiDB work.

**Describe the feature you'd like:**

Use session variable [`tidb-force-priority`](https://docs.pingcap.com/zh/tidb/v4.0/mydumper-overview#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE-mydumper-%E7%9A%84%E5%8F%82%E6%95%B0---tidb-force-priority) to set dumpling sqls priority to reduce the resources usage of tidb cluster.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lichunzhu** [comment]
Besides, should we support an argument to set session variables while dumpling?

**Comment by kennytm** [comment]
allowing arbitrary session variables sounds better. if we focus on priority, the question becomes why don't see also support `SELECT HIGH_PRIORITY` on MySQL.

**Comment by lichunzhu** [comment]
> allowing arbitrary session variables sounds better. if we focus on priority, the question becomes why don't see also support `SELECT HIGH_PRIORITY` on MySQL.

I think we can also support that for MySQL 😃

**Comment by kennytm** [comment]
there is no `SELECT LOW_PRIORITY` for MySQL so it's basically useless 🙃

**Comment by lichunzhu** [comment]
> there is no `SELECT LOW_PRIORITY` for MySQL so it's basically useless 🙃

Yes.. I found that `LOW_PRIORITY` can only be used for `insert` and `update` 😿

**Comment by kennytm** [comment]
With #167 this can be supported with `--params tidb_force_priority=LOW_PRIORITY`, so closing.
