### ISSUE TITLE
Unify `--filesize` and `--statement-size` definition with mydumper's

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#127]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently dumpling's `--filesize` and `--statement-size` only counts the column values' size. However, mydumper counts the text file's size, which may confuse users.

**Describe the feature you'd like:**

Unify `--filesize` and `--statement-size` definition with mydumper's which means sentences like 'INSERT' are also counted in filesize.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lichunzhu** [comment]
@kennytm WDYT?

**Comment by kennytm** [comment]
:+1:
