### ISSUE TITLE
Support clustered index

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#149]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently when clustered index is enabled, the `_tidb_rowid` column is missing (?). Dumpling will use `_tidb_rowid` to parallel dumping tables.

**Describe the feature you'd like:**

Support clustered index.

Reference: https://github.com/pingcap/tidb/pull/17044/files

**Describe alternatives you've considered:**

No alternatives.

**Teachability, Documentation, Adoption, Optimization:**

**Comment by overvenus** [comment]
@coocood PTAL, there is any workaround to allow dumpling to parallel dump a table?

**Comment by coocood** [comment]
We can select the region keys of a table, then construct select statements using where condition.

**Comment by lichunzhu** [comment]
> statements

Have we already supported this? Do we have any examples?

**Comment by coocood** [comment]
```
select start_key, table_id from information_schema.tikv_region_status s, information_schema.tables t where s.table_id = t.tidb_table_id and t.table_name = 't';

+--------------------------------------------------------------------------+----------+
| start_key                                                                | table_id |
+--------------------------------------------------------------------------+----------+
| 7480000000000000FF3C5F720137000000FF00000000F8013000FF000000000000F800FE |       60 |
| 7480000000000000FF3C5F720135000000FF00000000F8013000FF000000000000F800FE |       60 |
| 7480000000000000FF3C5F720133000000FF00000000F8013000FF000000000000F800FE |       60 |
| 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE |       60 |
| 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE |       60 |
+--------------------------------------------------------------------------+----------+
```

**Comment by overvenus** [comment]
> We can select the region keys of a table, then construct select statements using where condition.

Looks promising, though I still have few questions. 

What if there are multiple region split and merge, are they still correct?
How to make sure the results cover all necessary data?
How much data between two start keys?

**Comment by coocood** [comment]
1. yes
2. use the first query with '<', last query with '>', the middle query use 'between' operator.
3. about 96MB.

**Comment by lichunzhu** [comment]
How do we write a where sql now?

**Comment by coocood** [comment]
The start_key is encoded bytes, we need to decode it and get the handle value to construct the where condition.

**Comment by coocood** [comment]
```
select * from t where pk < {pk_value_1};
select * from t where pk >= {pk_value_1} and pk < {pk_value_2};
select * from t where pk >= {pk_value_2} and pk < {pk_value_3};
select * from t where pk >= {pk_value_3};
```

**Comment by lichunzhu** [comment]
> ```
> select * from t where pk < {pk_value_1};
> select * from t where pk >= {pk_value_1} and pk < {pk_value_2};
> select * from t where pk >= {pk_value_2} and pk < {pk_value_3};
> select * from t where pk >= {pk_value_3};
> ```

How to decode the `start_key`? Should we use `select tidb_decode_key( '7480000000000000FF2D5F720134323339FF39380000FD000000FC' );`?
Besides, I think it's better to decode `start_key` in tidb so that other applications can also use this feature.
For example, `select * from t where _start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;`

**Comment by coocood** [comment]
> > ```
> > select * from t where pk < {pk_value_1};
> > select * from t where pk >= {pk_value_1} and pk < {pk_value_2};
> > select * from t where pk >= {pk_value_2} and pk < {pk_value_3};
> > select * from t where pk >= {pk_value_3};
> > ```
> 
> How to decode the `start_key`? Should we use `select tidb_decode_key( '7480000000000000FF2D5F720134323339FF39380000FD000000FC' );`?
> Besides, I think it's better to decode `start_key` in tidb so that other applications can also use this feature.
> For example, `select * from t where _start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;`

Yes, we can use `tidb_decode_key`
```
+----------------------------------+----------+
| tidb_decode_key(start_key)       | table_id |
+----------------------------------+----------+
| tableID=58, clusterHandle={7, 0} |       60 |
| tableID=60, clusterHandle={3, 0} |       60 |
| tableID=60, clusterHandle={5, 0} |       60 |
| tableID=60, clusterHandle={7, 0} |       60 |
+----------------------------------+----------+
```

**Comment by coocood** [comment]
But the `tidb_decode_key` is not used for this.
It doesn't generate the string according to the column type, for simple types like int and string, it's fine, but for some types like datetime, it doesn't work.

**Comment by lichunzhu** [comment]
> For example, select * from t where _start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;

So can we support specifying `start_key` range in sql in the future, so that dumpling and other apps don't need to decode start_key?

**Comment by lzmhhh123** [comment]
> But the `tidb_decode_key` is not used for this.
> It doesn't generate the string according to the column type, for simple types like int and string, it's fine, but for some types like datetime, it doesn't work.

In my view. We can simply add `''` for each value instead to handle column type.

for this example:

```sql
+----------------------------------+----------+
| tidb_decode_key(start_key)       | table_id |
+----------------------------------+----------+
| tableID=58, clusterHandle={7, 0} |       60 |
| tableID=60, clusterHandle={3, 0} |       60 |
| tableID=60, clusterHandle={5, 0} |       60 |
| tableID=60, clusterHandle={7, 0} |       60 |
+----------------------------------+----------+
```

One of the sql can be writed as:

```sql
select * from t where ('3','0') <= (pkcol1, pkcol2) and (pkcol1, pkcol2) < ('7','0');
```

**Comment by lzmhhh123** [comment]
> > For example, select * from t where _start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;
> 
> So can we support specifying `start_key` range in sql in the future, so that dumpling and other apps don't need to decode start_key?
> 
> If you think this is ok, I can fire an issue in tidb repo and we can have a further discussion there.

You can file an issue in pingcap/tidb and label it `feature-request`. Then there are some people going to review the request.

**Comment by lichunzhu** [comment]
> > > For example, select * from t where _start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;
> > 
> > 
> > So can we support specifying `start_key` range in sql in the future, so that dumpling and other apps don't need to decode start_key?
> > If you think this is ok, I can fire an issue in tidb repo and we can have a further discussion there.
> 
> You can file an issue in pingcap/tidb and label it `feature-request`. Then there are some people going to review the request.

Already fired an issue https://github.com/pingcap/tidb/issues/19951

**Comment by overvenus** [comment]
@coocood PTAL, could you assign someone to resolve pingcap/tidb#19951?

**Comment by IANTHEREAL** [comment]
any updates? @coocood @overvenus @lichunzhu

**Comment by lichunzhu** [comment]
> any updates? @coocood @overvenus @lichunzhu

@tangenta updated the result of `tidb_decode_key` as json in https://github.com/pingcap/tidb/pull/20382
A PR to adapt this for dumpling is also released in https://github.com/pingcap/dumpling/pull/163

**Comment by lichunzhu** [comment]
All related PR has been merged. Need further test.

**Comment by glkappe** [comment]
Which version will this pr cherry-pick to?

**Comment by lichunzhu** [comment]
> Which version will this pr cherry-pick to?

This feature is already supported on TiDB 5.0.0+. But it's not cherry-picked to TiDB 4.0.x

**Comment by glkappe** [comment]
What is the reason why it cannot cherry-pick to 4.0.x? It is easy to encounter this problem when exporting large tables

**Comment by IANTHEREAL** [comment]
can we close it now?

**Comment by lichunzhu** [comment]
Already supported by `tablesample`.
