### ISSUE TITLE
--sql doesn't work with --where

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/dumpling#154]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

--sql for selecting columns
-- where for conditions

2. What did you expect to see?

it works

3. What did you see instead?

-- where was ignored.

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        (paste Dumpling version here)
        ```
4.0.6 

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        (paste source database version here)
        ```
3.0.5

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

**Comment by lichunzhu** [comment]
That meets our expectations. Can you write where condition into `--sql` option?

**Comment by kennytm** [comment]
we should probably make these two options mutually exclusive (error if both are set)

**Comment by CrazyNash** [comment]
> here condition into

Sure, it deserves a word in user doc

**Comment by lichunzhu** [comment]
Nice suggestion! We will refine it.
