### ISSUE TITLE
Support control impact on TiDB load while dumpling

### ISSUE THREAD

**Issue by Win-Man** [pingcap/dumpling#159]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The load of TiDB increase while backup the cluster via dumpling, and it influence the other SQL on the cluster.

**Describe the feature you'd like:**

`dumpling` could control impact on TiDB load while dumpling.
I can think of setting session variables like `tidb_distsql_scan_concurrency`, `tidb_mem_quota_query`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lichunzhu** [comment]
`--tidb-mem-quota-query` can be configured in dumpling arguments. `tidb_distsql_scan_concurrency` is also in plan.

**Comment by Win-Man** [comment]
Thanks for the reply, could you tell me when will dumpling support `tidb_distsql_scan_concurrency`?

**Comment by lichunzhu** [comment]
After https://github.com/pingcap/dumpling/pull/167 is merged, you can set `tidb_distsql_scan_concurrency` through `--params "tidb_distsql_scan_concurrency=xxx"`. Is that okay?

**Comment by Win-Man** [comment]
@lichunzhu Thanks for your reply, I checked the pr have merged so I close this issue.
