### ISSUE TITLE
Support -F even specified -r

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dumpling#164]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

We can dump a single table concurrently with `-r`, but we may also want to limit the file size with `-F`.

We may support `-r` and `-F` to be specified in one dump round and rotate to a new file when `-r` reached or `-F` reached.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lichunzhu** [comment]
Dumped sql will be labeled as `name.rowIndex.fileIndex.sql` at first. After the dumping process finished, `dumpling` will rename these files to set index from 1 to X.
