### ISSUE TITLE
Support --complete-insert

### ISSUE THREAD

**Issue by pcqz** [pingcap/dumpling#168]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
When dest table has more columns than source table，we need dump insert sqls that include column names.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by lichunzhu** [comment]
Is this duplicate with https://github.com/pingcap/dumpling/issues/134?
