### ISSUE TITLE
-F parameter is not effect，when -r parameter add？

### ISSUE THREAD

**Issue by lddlww** [pingcap/dumpling#171]
dumpling cmd：
```
dumpling  -uroot -P4000 -h10.59.111.117 --filetype sql --threads 64 -F256MiB -r 1000000  -o /data/bak/bi -Bbi -Tbi.spl_click_android -Tbi.spl_android_startup_record -Tbi.spl_click_ios -Tbi.nature_channel -Bdsp
```

outfile size is more than 256MiB，looks that -F is not invalid

**Comment by lichunzhu** [comment]
Can you use `dumpling -V` to show me which version of dumpling are you using?
Besides, what is the file size for each file?

**Comment by lddlww** [comment]
```
Release version: v4.0.7
Git commit hash: 48b61dc62c7e27c99b81d939e4614f07e3f3a9d2
Git branch:      heads/refs/tags/v4.0.7
Build timestamp: 2020-09-29 06:52:06Z
Go version:      go version go1.13 linux/amd64
```



> what is the file size for each file


files size is not fix

**Comment by lichunzhu** [comment]
When `-r` argument is given, `-F` argument will be omited. After https://github.com/pingcap/dumpling/issues/164 they can both take effect.

**Comment by lddlww** [comment]
oh，thanks for remind

**Comment by lichunzhu** [comment]
I will close this issue now. You can trace this problem in 164.
