### ISSUE TITLE
Judge table has no data wrong

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/dumpling#186]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

I create a table with a unique key `id`, it can be null value and int type. I then insert values into the table with `id` column null.

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v4.0.8-3-g3fe8a47-dev
Git commit hash: 3fe8a47656674268bfe66f34a8ad70f8483e0f4d
Git branch:      master
Build timestamp: 2020-11-04 11:43:30Z
Go version:      go version go1.13.6 linux/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        (paste source database version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

The step like:
1>   create table t5 with a unique key id, int type and can be null.

CREATE TABLE `test`.`t5` (
  `id` int(11) DEFAULT NULL,
  `name` char(6) COLLATE utf8mb4_bin DEFAULT '',
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

2> insert values witch column id null, data like this:
     mysql> select * from t5;
+------+--------+
| id   | name   |
+------+--------+
| NULL | xiaomi |
| NULL | xiaoho |
+------+--------+
2 rows in set (0.00 sec)

3> dumpilng table t5 args:

 ./dumpling -T "test.t5" -u user -p password -h host -P port -r 1

4> it dumped no data, because it judge table has no data.

https://github.com/pingcap/dumpling/blob/master/v4/export/ir_impl.go:  line 190

func splitTableDataIntoChunks(
	...

	query := fmt.Sprintf("SELECT MIN(`%s`),MAX(`%s`) FROM `%s`.`%s` ",
		escapeString(field), escapeString(field), escapeString(dbName), escapeString(tableName))
	if conf.Where != "" {
		query = fmt.Sprintf("%s WHERE %s", query, conf.Where)
	}
	log.Debug("split chunks", zap.String("query", query))

	var smin sql.NullString
	var smax sql.NullString
	row := db.QueryRowContext(ctx, query)
	err = row.Scan(&smin, &smax)
	if err != nil {
		log.Error("split chunks - get max min failed", zap.String("query", query), zap.Error(err))
		errCh <- withStack(err)
		return
	}
	if !smax.Valid || !smin.Valid {
		// found no data
		log.Warn("no data to dump", zap.String("schema", dbName), zap.String("table", tableName))
		close(tableDataIRCh)
		return
	}

5> in the case, smax and smin will be null value and return. Actually, t5 has two rows.

**Comment by lichunzhu** [comment]
Yes. We should send a signal to the channel `linear` when this situation happens. Could you please help us refine this?

**Comment by jiyfhust** [comment]
> Yes. We should send a signal to the channel `linear` when this situation happens. Could you please help us refine this?

ok, i am pleased to do that, i will have a try.

**Comment by lichunzhu** [comment]
Thanks!
