### ISSUE TITLE
Dump data order by primary key, get primary key column may lead to a problem

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/dumpling#187]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

https://github.com/pingcap/dumpling/blob/master/v4/export/sql.go ： line 308

Get primary may lead to a problem.    

     function :   GetPrimaryKeyName

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v4.0.8-3-g3fe8a47-dev
Git commit hash: 3fe8a47656674268bfe66f34a8ad70f8483e0f4d
Git branch:      master
Build timestamp: 2020-11-04 11:43:30Z
Go version:      go version go1.13.6 linux/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        (paste source database version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

Potential problems  like this:

1> A table has a joint-index as primary key.

CREATE TABLE `t6` (
  `id` int(11) NOT NULL DEFAULT '0',
  `name` char(6) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`name`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

2> get primary key column will get a random column from primary index column.

https://github.com/pingcap/dumpling/blob/3fe8a47656674268bfe66f34a8ad70f8483e0f4d/v4/export/sql.go#L337

actually, it can get column id or name randomly.

https://github.com/pingcap/dumpling/blob/3fe8a47656674268bfe66f34a8ad70f8483e0f4d/v4/export/sql.go#L286

but i need a sort is ： order by name, id.

In addition, it can lead a  performance Issues to mysql server  when it choose "order by id".

i think "show index from tbname" can be better, and can get full primary columns.

**Comment by lichunzhu** [comment]
Yes. IMO
1. We should sort table by full primary keys.
2. We should make sort by primary key as an option.

**Comment by jiyfhust** [comment]
I think  it is a good idea.

**Comment by lichunzhu** [comment]
@kennytm WDYT?
@jiyfhust Could you please also help to fix this issue?

**Comment by jiyfhust** [comment]
Ok, i will have a try to fix it.

**Comment by lichunzhu** [comment]
Thanks a lot!

**Comment by kennytm** [comment]
@lichunzhu 

> We should sort table by full primary keys.

SGTM

> We should make sort by primary key as an option.

i think we should always sort by PK when the source is MySQL, MariaDB, or TiDB with clustered index. not sure about TiDB with alter-pk though.

so for TiDB source, we have got a "system" sort order and "primary-key" sort order 🤔

**Comment by jiyfhust** [comment]
Hi, i submited a pr for this issue. In the TiDB not with clustered index case，it will sort by _tidb_rowId,  others will by primary keys.

**Comment by lichunzhu** [comment]
This issue has already been finished by https://github.com/pingcap/dumpling/pull/196.
