### ISSUE TITLE
Using Dumpling to export MySQL and TiDB schema is inconsistent

### ISSUE THREAD

**Issue by yilongrong** [pingcap/dumpling#193]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Using Dumpling to export MySQL and TiDB schema is inconsistent

**Describe the feature you'd like:**

Using Dumpling to export MySQL include information, MySQL schema, but TiDB does not include these schemas

**Describe alternatives you've considered:**

TiDB and MySQL should keep the same export information. 

**Teachability, Documentation, Adoption, Optimization:**

![image](https://user-images.githubusercontent.com/55389305/98511272-73084b80-229f-11eb-8f92-7cdde1ed4874.png)

**Comment by lichunzhu** [comment]
fixed by https://github.com/pingcap/dumpling/pull/194
