### ISSUE TITLE
Dumpling dumps slower than TiDB's `select into outfile`

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#213]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Use dumpling to dump TiDB's data in one single thread and dump all data into one file.

2. What did you expect to see?
Dumpling takes more time than TiDB.

3. What did you see instead?
Dumpling should be faster or equal to TiDB. We should investigate whether there is something that we can optimize.

**Comment by kennytm** [comment]
Can you quantify how much slower?

**Comment by lichunzhu** [comment]
> Can you quantify how much slower?

I'm doing a test and will paste the result here later.

**Comment by lichunzhu** [comment]
Testing tpcc 20GB data result:

Dumpling --sql:
commit: a8a54d059f88e8ed0be62c3d8338d32856b53985
2m30.500s

TiDB select into outfile:
TiDB commit: 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
2 min 44.43 sec

Mydumper (dumpling 20GB files into one file):
1 min 31.634s

In the above tests, dumpling/mydumper and TiDB are in one machine. Need more tests on the other environment.

**Comment by overvenus** [comment]
About 98G dumped file.

<details>

![image](https://user-images.githubusercontent.com/2150711/101346347-5de50380-38c3-11eb-9858-214302a9949a.png)

</details>

**Comment by lichunzhu** [comment]
Generate 26GB data with the same table structure on a TiDB cluster with 1 PD/TiKV/TiDB.
The dump time cost result comparison:
TiDB: 5 min 44.27 sec
dumpling -T v4.0.7: 6m27.704s
dumpling --sql: 6m20.779s
newest dumpling --sql: 6m10.481s
newest dumpling -T: 6m9.262s

**Comment by lichunzhu** [comment]
Start another test on the environment before. The dump result is 114G/28min. TiDB select into file result is 98G/24min.

There is no big difference between them. I also the flame graph of new dumpling. No explicit performance problem is found.

![image](https://user-images.githubusercontent.com/21104942/102043777-50260580-3e10-11eb-9fec-6358d0bbeaa1.png)

I think we can close this issue temporally.
