### ISSUE TITLE
dumpling should fail when provided positional parameters to CLI

### ISSUE THREAD

**Issue by glkappe** [pingcap/dumpling#225]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
https://asktug.com/t/topic/67342
![image](https://user-images.githubusercontent.com/21033020/103282276-37bd0a00-4a10-11eb-9106-a061bf52275c.png)

And no detailed execution statements are output in debug mode
[debug_test.log](https://github.com/pingcap/dumpling/files/5750576/debug_test.log)

2. What did you expect to see?
All exported data

3. What did you see instead?
Report an error

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        (paste Dumpling version here)
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        (paste source database version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

**Comment by kennytm** [comment]
What to do: Basically throw an error in `main.go` if `pflag.NArg()` is not 0.
