### ISSUE TITLE
Support adaptive export configuration based on TiDB instance configuration to avoid TiDB OOM

### ISSUE THREAD

**Issue by overvenus** [pingcap/dumpling#232]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There are some configurations in Dumpling to control export speed and memory consumption (of TiDB). Inappropriate configurations can easily cause TiDB OOM, e.g., pingcap/tidb#22306.

To prevent TiDB OOM we need to support adaptive adjusting export configurations based on TiDB instance (e.g., total memory of TiDB)

Cc #104

**Comment by lichunzhu** [comment]
Possible Solutions

---

### Set adaptive/fixed `--rows` arguments by default

pros: users don't need to learn how to set `--rows` and other arguments to reduce memory usage.
cons: dumpling will generate several files, which is not the default behavior for `mydumper`. This may confuse users.

### Separate the dumping whole table command to several small subcommands and concatenate their results in one file

pros: avoid generating several files and can reduce memory usage.
cons: none
notes: 
1. In TiDB v5.0.0 we can easily split the table by `table sample. But we need to think about other databases and other versions of TiDB.
2. We need to be careful about how to make sure the data is still in-order like directly select all from one table.

### Reduce the `sort by` usage

pros: some `sort by` suffix might be useless. They may increase the memory usage of the TiDB.
cons: some scenes need ordered data. We need to be careful about this.

**Comment by lichunzhu** [comment]
already implemented.
