### ISSUE TITLE
Dumpling reports "overflows bigint" in some corner cases

### ISSUE THREAD

**Issue by tangenta** [pingcap/dumpling#235]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```sql
mysql> create table t (a bigint auto_increment primary key);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values (1), (9223372036854775807);
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

```

Run dumpling with `--rows 1`

2. What did you expect to see?

Dump successfully.

3. What did you see instead?
```console
dump failed: Error 1690: constant 9223372036854775809 overflows bigint
```

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
       5e6981efa173ff525abb31c6e62a50ecd6da6a09
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        TiDB-v5.0.0-rc-3-g5f3709cd6
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

**Comment by lichunzhu** [comment]
Can you paste the dumpling's log here?

**Comment by tangenta** [comment]
I found that this is a bug in TiDB-v5.0.0-rc, not Dumpling.

Fixing PR: https://github.com/pingcap/tidb/pull/21805
