### ISSUE TITLE
there's mysql database generated automatically while using config -f "*.*"

### ISSUE THREAD

**Issue by minipeanut** [pingcap/dumpling#268]
## Bug Report

1. What did you do? If possible, provide a recipe for reproducing the error.

./dumpling -u root -h xx -P 4000 -o /data0/dumpling/test0001/ -f "*.*"

2. What did you expect to see?

![image](https://user-images.githubusercontent.com/42461752/114387103-a2abde80-9bc4-11eb-8553-d18af4220a63.png)

3. What did you see instead?
![image](https://user-images.githubusercontent.com/42461752/114387234-c707bb00-9bc4-11eb-9dc0-0b3338f608d3.png)

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v5.0.0-nightly
        Git commit hash: a0bbe7c67b41dfcfa2cedfd97ddde956863b35ef
        Git branch:      heads/refs/tags/v5.0.0-nightly
        Build timestamp: 2021-03-29 02:46:06Z
        Go version:      go version go1.13 linux/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        5.7.25-TiDB-v5.0.0-nightly
        ```

**Comment by lichunzhu** [comment]
This is an expected behavior to support dumping system tables. The default --filter configuration will exclude all these system tables.
default --filter: `-f *.* -f !/^(mysql|sys|INFORMATION_SCHEMA|PERFORMANCE_SCHEMA|METRICS_SCHEMA|INSPECTION_SCHEMA)$/.*`

**Comment by cyliu0** [comment]
@lichunzhu Should we change the document mentioned in this issue?

**Comment by lichunzhu** [comment]
> @lichunzhu Should we change the document mentioned in this issue?

Yes. We need to update this document.
