### ISSUE TITLE
there's info level log on the console with config: --loglevel "fatal"  --logfile "/xx/xx"

### ISSUE THREAD

**Issue by minipeanut** [pingcap/dumpling#269]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
        ```
        ./dumpling -u root -h xx -P 4000 -o /data0/dumpling/test3054/ -f "sbtest.sbtest1" --sql "select * from sbtest.v1" --logfmt "text" --loglevel "fatal" --logfile "/root/3054.log"
        ```

2. What did you expect to see?
if there's no log above the fatal level, there shouldn't be any log except some necessary information.the info on the console and written in the log file should be consistent.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/42461752/114490464-800ed980-9c47-11eb-8cd7-1c189ff26a95.png)

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v5.0.0-nightly
        Git commit hash: a0bbe7c67b41dfcfa2cedfd97ddde956863b35ef
        Git branch:      heads/refs/tags/v5.0.0-nightly
        Build timestamp: 2021-03-29 02:46:06Z
        Go version:      go version go1.13 linux/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        5.7.25-TiDB-v5.0.0-nightly
        ```

**Comment by lichunzhu** [comment]
@minipeanut Thanks for your notification. We will fix the problem in #270.
