### ISSUE TITLE
make dumpling adapted to old version TiDB problems

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#281]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Old versions' TiDB has some bugs. Sometimes it's much easier to avoid these problems on dumpling rather than on TiDB.

**Describe the feature you'd like:**

---
### wrong TiDB information.schema result
BUG: TiDB's `information_schema.columns` and `information_schema.tables` will miss some information if we `drop <database>` and then set a `tidb_snapshot` to dump dropped data.
Affected version: TiDB v3.0.5
Fix PR:

**Comment by IANTHEREAL** [comment]
can we close it now?

**Comment by lichunzhu** [comment]
https://github.com/pingcap/dumpling/pull/305 has fixed this PR. Because we use `show table status` to replace `intomation_schema.tables`.
