### ISSUE TITLE
DDL during dumping will cause MySQL dead lock

### ISSUE THREAD

**Issue by lance6716** [pingcap/dumpling#296]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```diff
diff --git a/v4/export/dump.go b/v4/export/dump.go
index 947f187..41ea533 100755
--- a/v4/export/dump.go
+++ b/v4/export/dump.go
@@ -219,6 +219,8 @@ func (d *Dumper) Dump() (dumpErr error) {
                tctx.L().Error("fail to get estimate total count", zap.Error(err))
        }

+       time.Sleep(30*time.Second)
+
        if conf.SQL == "" {
                if err = d.dumpDatabases(writerCtx, metaConn, taskChan); err != nil && !errors.ErrorEqual(err, context.Canceled) {
                        return err
```

build a dumpling and

```bash
./dumpling -h 127.0.0.1 -P 3306 -u root -p 123456 -T all_mode.t1
```

before 30 seconds pass,

```mysql
MySQL [all_mode]> alter table t1 add column new_col1 int;
```

2. What did you expect to see?

dump success

3. What did you see instead?

both dumpling and DDL stuck forever.

after kill dumpling, DDL could resume

```mysql
MySQL [all_mode]> alter table t1 add column new_col1 int;
Query OK, 0 rows affected (1 min 55.673 sec)
```

4. Versions of the cluster

master

**Comment by dveeden** [comment]
[`LOCK INSTANCE FOR BACKUP`](https://dev.mysql.com/doc/refman/8.0/en/lock-instance-for-backup.html) could help here if MySQL 8.0 is used
