### ISSUE TITLE
Parallel dump tables

### ISSUE THREAD

**Issue by cyliu0** [pingcap/dumpling#297]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We tried to dump more than 20k tables with only 10 rows per table. It will be too slow like 1900 tables per hour.

**Describe the feature you'd like:**

I'd like parallel dump tables support. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
Please post the dumpling parameters, and number of vCPUs of the machine

**Comment by cyliu0** [comment]
I've tested this on a 40 cpus host with default dumpling parameters. And I got a temporary version from @lichunzhu . That one is fast enough I believe. It dumped 28k+ tables in 5 minutes. And it will be merged.

> [2021/06/21 15:36:01.746 +08:00] [INFO] [collector.go:212] ["backup Success summary: total backup ranges: 56930, total success: 56930, total failed: 0, total take(backup time): 5m5.578083543s, total take(real time): 5m5.578115117s, total size(MB): 204.24, avg speed(MB/s): 0.67, total rows: 2655787"]

**Comment by lichunzhu** [comment]
The main reason is the query from `information.columns` is too slow. Parallel may not help much.

**Comment by kennytm** [comment]
why are information_schema on both Aurora and TiDB slow 🤦
