### ISSUE TITLE
Improve handling of `START TRANSACTION` with MySQL-like databases

### ISSUE THREAD

**Issue by dveeden** [pingcap/dumpling#309]
## Bug Report

The SQL query from [sql.go](https://github.com/pingcap/dumpling/blob/ef07f40b83d6b72a37542c4b65f9ddccc132a84a/v4/export/sql.go#L625) has a version specific comment to only execute on MySQL 4.1.8.
```
query = "START TRANSACTION /*!40108 WITH CONSISTENT SNAPSHOT */"
```

However with [Vitess](https://github.com/pingcap/docs/pull/5783#issuecomment-863196625) and MemSQL/SingleStore seems to have the same issue.

I would suggest to run a `START TRANSACTION` without the version-specific comment if the original statement fails.

Also with `--consistency none` this still fails.

**Comment by SunRunAway** [comment]
I suggest we should do a full test for memsql/singlestore.

**Comment by dveeden** [comment]
https://docs.singlestore.com/db/v7.3/en/reference/sql-reference/data-manipulation-language-dml/begin.html indeed doesn't show the `WITH CONSISTENT SNAPSHOT`.

**Comment by dveeden** [comment]
> I suggest we should do a full test for memsql/singlestore.

Yes and maybe Vitess. But as Vitess has a set of MySQL servers as backend and dumping directly from those and combining the data should work. However that could complicate table names and might copy Vitess specific metadata that should have been excluded.
