### ISSUE TITLE
dump TiDB INFORMATION_SCHEMA failed 

### ISSUE THREAD

**Issue by siddontang** [pingcap/dumpling#33]
```
[2020/03/01 21:07:14.710 +08:00] [WARN] [session.go:1123] ["compile SQL failed"] [conn=51] [error="[planner:1054]Unknown column '_tidb_rowid' in 'field list'"] [SQL="SELECT _tidb_rowid from INFORMATION_SCHEMA.INSPECTION_RESULT LIMIT 0"]
```

Seem table `INSPECTION_RESULT` has no `_tidb_rowid`

**Comment by siddontang** [comment]
```
[2020/03/04 10:06:28.131 +08:00] [ERROR] [main.go:93] ["dump failed"] [error="err = Error 1105: other error: Column ID -1 of table cluster_processlist not found
```

**Comment by siddontang** [comment]
seem we can dump a table with no PRIMARY key.

**Comment by GregoryIan** [comment]
You are too concise. Others can't figure out the situation, I will explain in detail later @siddontang

**Comment by siddontang** [comment]
I found we can't handle TiDB INFORMATION SCHEMA correctly, another error:

```
[2020/03/04 10:57:09.226 +08:00] [ERROR] [main.go:93] ["dump failed"] [error="err = Error 1105: denied to scan full logs (use `SELECT * FROM cluster_log WHERE message LIKE '%'` explicitly if intentionally)
```

**Comment by siddontang** [comment]
I think we should ignore dumping the diagnosing table of TiDB.

**Comment by GregoryIan** [comment]
` ["dump failed"] [error="err = Error 1105: can not get 'tikv_gc_safe_point'\`

**Comment by tangenta** [comment]
@siddontang I will fix them after #30 merged.
@GregoryIan This is because mocktikv doesn't have `gc_safe_point`.

**Comment by GregoryIan** [comment]
I know the reason, but I think the behavior is very inconsistent

**Comment by GregoryIan** [comment]
I use TiUP run a playground, then
```
 mysql> SELECT * FROM INFORMATION_SCHEMA.SLOW_QUERY LIMIT 1;
ERROR 1105 (HY000): open tidb-slow.log: no such file or directory
```

**Comment by tangenta** [comment]
> I know the reason, but I think the behavior is very inconsistent in different storages, it would make tools in trouble @tangenta

The default `consistency` config option is `snapshot` for TiDB. Should we change the default value to `lock` or `none` in order to solve the above problem?

`lock` indicates that every table's read lock will be acquired before the dump.
"None" indicates that the user should promise that no mutations will occur in the table during the dump.



> I use TiUP run a playground, then
> 
> ```
> mysql> SELECT * FROM INFORMATION_SCHEMA.SLOW_QUERY LIMIT 1;
> ERROR 1105 (HY000): open tidb-slow.log: no such file or directory
> ```

I will add `information_schema` to the blacklist.

**Comment by GregoryIan** [comment]
At present, it seems that the best way is to add `information_schema` or the diagnosing table of TiDB  into the blacklist

**Comment by GregoryIan** [comment]
> ```
> [2020/03/04 10:06:28.131 +08:00] [ERROR] [main.go:93] ["dump failed"] [error="err = Error 1105: other error: Column ID -1 of table cluster_processlist not found\ngoroutine 44 [running]:\nruntime/debug.Stack(0x15cff80, 0xc000191080, 0x15d0c80)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/pingcap/dumpling/v4/export.withStack(0x15cff80, 0xc000191080, 0xc0000b4008, 0xc000228000)\n\t/Users/tangliu/program/dumpling/v4/export/error.go:40 +0x8d\ngithub.com/pingcap/dumpling/v4/export.SelectAllFromTable(0xc0001ce160, 0xc0001d00c0, 0x7ffeefbffa09, 0x12, 0xc000192460, 0x13, 0x13, 0xc00038e000, 0x1f3, 0x0)\n\t/Users/tangliu/program/dumpling/v4/export/sql.go:76 +0x28b\ngithub.com/pingcap/dumpling/v4/export.dumpTable(0x15d9b20, 0xc0000b4008, 0xc0001ce160, 0xc0001d00c0, 0x7ffeefbffa09, 0x12, 0xc000192460, 0x13, 0x15d7f20, 0xc00018e070, ...)\n\t/Users/tangliu/program/dumpling/v4/export/dump.go:90 +0x151\ngithub.com/pingcap/dumpling/v4/export.dumpDatabases.func1(0x0, 0x0)\n\t/Users/tangliu/program/dumpling/v4/export/dump.go:70 +0x170\ngolang.org/x/sync/errgroup.(*Group).Go.func1(0xc00018ac90, 0xc000188de0)\n\t/Users/tangliu/program/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\t/Users/tangliu/program/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66\n"] [stack="main.run\n\t/Users/tangliu/program/dumpling/cmd/dumpling/main.go:93\nmain.glob..func1\n\t/Users/tangliu/program/dumpling/cmd/dumpling/main.go:47\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/tangliu/program/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/tangliu/program/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/tangliu/program/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885\nmain.main\n\t/Users/tangliu/program/dumpling/cmd/dumpling/main.go:100\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]
> ```

```
mysql> SELECT _tidb_rowid FROM INFORMATION_SCHEMA.CLUSTER_PROCESSLIST limit 0;
Empty set (0.02 sec)
```

now dumplings can't tell if `INFORMATION_SCHEMA.CLUSTER_PROCESSLIST` really has _tidb_rowid

**Comment by GregoryIan** [comment]
@tangenta how can dumplings determine what storage is used by TiDB?

**Comment by GregoryIan** [comment]
some error log while I use `mydumper` to dump `INFORMATION_SCHEMA`

```** (mydumper:29948): CRITICAL **: 01:30:03.714: Error dumping table (INFORMATION_SCHEMA.CLUSTER_LOG) data: denied to scan full logs (use `SELECT * FROM cluster_log WHERE message LIKE '%'` explicitly if intentionally)

** (mydumper:29948): CRITICAL **: 01:30:05.051: Error dumping table (INFORMATION_SCHEMA.METRICS_SUMMARY) data: execute 'select sum(value),avg(value),min(value),max(value) from `metrics_schema`.`abnormal_stores` where time>='2020-03-04 14:00:04.064' and time<='2020-03-04 14:30:04.064'' failed: query metric error, msg: server error: 500, detail: metric storage doesn't set


** (mydumper:29948): CRITICAL **: 01:30:05.081: Error dumping table (INFORMATION_SCHEMA.METRICS_SUMMARY_BY_LABEL) data: execute 'select sum(value),avg(value),min(value),max(value),`instance`,`type` from `metrics_schema`.`abnormal_stores` where time>='2020-03-04 14:00:04.084' and time<='2020-03-04 14:30:04.084' group by `instance`,`type` order by `instance`,`type`' failed: query metric error, msg: server error: 500, detail: metric storage doesn't set```

**Comment by GregoryIan** [comment]
if https://github.com/pingcap/tidb/issues is resolved, I want to let `dumpling` skip the `view` and `diagnosis` table. 

@kennytm @tangenta what do you think of it?

**Comment by kennytm** [comment]
#30 can already skip VIEWs.

**Comment by GregoryIan** [comment]
@kennytm we can ehance #30 now
