### ISSUE TITLE
dump data may be trimmed trailing space

### ISSUE THREAD

**Issue by lance6716** [pingcap/dumpling#351]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

https://asktug.com/t/topic/153095/9

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        (paste Dumpling version here)
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        (paste source database version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

**Comment by kennytm** [comment]
`cust_taxcode` is a `CHAR(20)`? `VARCHAR(20)`?

**Comment by lichunzhu** [comment]
Can't reproduce in the same environment. According to user's newly added description, it's not a dumpling problem.
```
不对，应该是我描述有点问题：在使用dumpling导出的时候数据的空格仍然存在，但是在使用 loader 将数据导入到mysql中的时候，空格被trim 掉了
```
