### ISSUE TITLE
dumpling does not create directories by default

### ISSUE THREAD

**Issue by glkappe** [pingcap/dumpling#398]
### What did you do?

tiup dumpling:v5.2.2 --host 172.16.4.210 --user root --port 24000 -o ./

### What did you expect to see?

dumpling can automatically create a directory with a timestamp. For example, dumpling-20210101235959

### What did you see instead?

A pile of scattered documents

### Versions of the cluster

dumpling v5.2.2.

**Comment by lichunzhu** [comment]
Try `tiup dumpling:v5.2.2 --host 172.16.4.210 --user root --port 24000` without specifying `-o`?

**Comment by glkappe** [comment]
Yes, a directory will be created at this time, `export-2021-11-25T05:27:32Z`
But can the file name be replaced by `dumpling-timestamp`, the word `export` is not discernible

**Comment by lichunzhu** [comment]
Do you mean changing the default name template? I think we need a further discussion with others.
For now, you can use -o ./dumpling-`date "+%Y%m%d%H%M%S"`

**Comment by glkappe** [comment]
Okay, please help with technical evaluation, thank you very much

**Comment by lichunzhu** [comment]
@sunzhaoyang could you please help take a look?

**Comment by glorv** [comment]
I wander how many users need this feature since it can be easily satisfied by a little shell skill. e.g. You can do this easily by type ```...-o dump-`date +%Y%m%d%H%M%S` ```.

Would you mind learn a little shell instead @glkappe . 😅

**Comment by lichunzhu** [comment]
close this now. It's a feature request.
