### ISSUE TITLE
Add ci pipelines, official documents and more tests in dumpling

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/dumpling#66]
- [x] Add official documents in https://github.com/pingcap/docs-cn @YuJuncen 

- [x] Add -T/--tables-list argument like mydumper 
- [x] Add black-white filter to replace -x argument in mydumper 

- [ ] Improve performance

- [x] Add more tests to dump data in different scenes [ask QA for test cases] @lichunzhu 

    Correctness test:

    * [x] TiDB feature

    Performance test:

    * [x] dump TB level data and make sure it's correct.
    * [x] dump TB level data and each table has 

- [x] Add release pipelines[ask PM] @lichunzhu 

- [x] Publish dumpling [Due time: 4.0.1]

**Comment by YuJuncen** [comment]
Seems CI pipelines is already enabled?

**Comment by lichunzhu** [comment]
> Seems CI pipelines is already enabled?

I mean add dumpling to official release CI pipelines.

**Comment by GregoryIan** [comment]
What cases are currently lacking in dumplings, and how to complete them, you can make a plan @YuJuncen 😄
