### ISSUE TITLE
Usability improvement with cmd line parameter `-t` and `-F`

### ISSUE THREAD

**Issue by amyangfei** [pingcap/dumpling#76]
## Background

- `-t` controls how many tables can be exported concurrently. If user provides `-r` in parameter, each table could be separated into some concurrent export jobs. So the `-t` doesn't mean exactly the upper limit of export threads.
- `-F` only accepts an integer, which represents the size of the output file in bytes. User may want to provide a more human-readable parameter such as `64MB`, `1GB`.

## Requirement

- `-t` controls the global upper limit of export threads, or provides another parameter to limit the concurrency of single table export, then the global concurrency can be controlled.
- `-F` accepts human readable file size

**Comment by kennytm** [comment]
I'm splitting the `-t` part into another issue for v4.0.3. The `-F` part has been fixed in #86.
