### ISSUE TITLE
Consider making dumpling `-F` flag use `MB` unit

### ISSUE THREAD

**Issue by tennix** [pingcap/dumpling#84]
Dumpling and Mydumper have the same command line flag `-F`, but the unit is totally different, Mydumper `-F` unit is `MB` while Dumpling `-F` unit is bytes.

Also, there is no `unit` in the `--help` document and `bytes` is not user-friendly if users want to configure 64MB, they have to specify `67108864` which is cumbersome.

Users would easily make mistakes if they used Mydumper previously, especially we link Mydumper document in Dumpling document.

**Comment by kennytm** [comment]
Duplicate of #76.
