### ISSUE TITLE
dumpling use `-H` to set host, but mydumper use `-h`

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/dumpling#85]
User may use mydumper before, and then use dumpling to replace mydumper, but dumpling has different flag with mydumper, for `host`, dumpling use `-H`,  but mydumper use `-h`.

**Comment by kennytm** [comment]
Every TiDB tools use `-h` to mean `--help`.

Meanwhile every MySQL-based tools use `-h` to mean `--host`.

The question is which side we want to take.
