### ISSUE TITLE
How to dump views?

### ISSUE THREAD

**Issue by cyliu0** [pingcap/dumpling#93]
I don't see how to dump views with option like this one `-W, --no-views                Do not dump views (default true)`

**Comment by kennytm** [comment]
You could write `--no-views=false` to dump views. Note however that views are not yet supported. Once it is supported on Dumpling as well as Lightning, this flag's default value will be changed to false.

**Comment by cyliu0** [comment]
> You could write `--no-views=false` to dump views. Note however that views are not yet supported. Once it is supported on Dumpling as well as Lightning, this flag's default value will be changed to false.

I see. Will we support it in 4.0.2? The option description is a little bit confusing right now.

**Comment by kennytm** [comment]
Likely not.
