### ISSUE TITLE
`--escape-backslash=false` leads to data mismatched

### ISSUE THREAD

**Issue by cyliu0** [pingcap/dumpling#98]
```
mysql root@127.0.0.1:test> create table t (a varchar(100))
Query OK, 0 rows affected
Time: 0.005s
mysql root@127.0.0.1:test> insert into t values("'hello")
Query OK, 1 row affected
Time: 0.003s
mysql root@127.0.0.1:test> select * from t
+--------+
| a      |
+--------+
| 'hello |
+--------+
1 row in set
Time: 0.014s

bash> ./bin/dumpling --filetype csv --escape-backslash=false
bash> cat export-2020-06-09T16:31:45+08:00/test.t.0.csv
"a"
"''hello"
```

The `'hello` became `''hello`

**Comment by cyliu0** [comment]
BTW, the option description is not totally correct. It escapes not only quotation marks but also characters like `\`.
`--escape-backslash        use backslash to escape quotation marks (default true)`

**Comment by lichunzhu** [comment]
> BTW, the option description is not totally correct. It escapes not only quotation marks but also characters like `\`.
> `--escape-backslash use backslash to escape quotation marks (default true)`

Yes, `--escape-backslash` doesn't merely escape quotation marks. I will update the description.

**Comment by lichunzhu** [comment]
> ```
> mysql root@127.0.0.1:test> create table t (a varchar(100))
> Query OK, 0 rows affected
> Time: 0.005s
> mysql root@127.0.0.1:test> insert into t values("'hello")
> Query OK, 1 row affected
> Time: 0.003s
> mysql root@127.0.0.1:test> select * from t
> +--------+
> | a      |
> +--------+
> | 'hello |
> +--------+
> 1 row in set
> Time: 0.014s
> 
> bash> ./bin/dumpling --filetype csv --escape-backslash=false
> bash> cat export-2020-06-09T16:31:45+08:00/test.t.0.csv
> "a"
> "''hello"
> ```
> 
> The `'hello` became `''hello`

@cyliu0 
''hello is sql-readable string, and I think this matches my exceptation. What do you want to get actually?

**Comment by cyliu0** [comment]
I think it should be `'hello`. Now there is an extra `'`. And I don't get anything from the reference doc... What's your point of `sql-readable string`?
```
mysql root@127.0.0.1:test> select "'hello" = "''hello"
+----------------------+
| "'hello" = "''hello" |
+----------------------+
| 0                    |
+----------------------+
1 row in set
Time: 0.012s
mysql root@127.0.0.1:test> select "'hello" = "'hello"
+---------------------+
| "'hello" = "'hello" |
+---------------------+
| 1                   |
+---------------------+
1 row in set
Time: 0.015s
```

**Comment by lichunzhu** [comment]
> I think it should be `'hello`. Now there is an extra `'`. And I don't get anything from the reference doc... What's your point of `sql-readable string`?
> 
> ```
> mysql root@127.0.0.1:test> select "'hello" = "''hello"
> +----------------------+
> | "'hello" = "''hello" |
> +----------------------+
> | 0                    |
> +----------------------+
> 1 row in set
> Time: 0.012s
> mysql root@127.0.0.1:test> select "'hello" = "'hello"
> +---------------------+
> | "'hello" = "'hello" |
> +---------------------+
> | 1                   |
> +---------------------+
> 1 row in set
> Time: 0.015s
> ```

If dumpling's --escape-backslash=false, dumpling will use `''` to replace `'` to make sure the output string can be load into database again.
Dumpling use `'` as quotation so you'd better try this
```
mysql> select '\'hello' = '''hello';
+-----------------------+
| '\'hello' = '''hello' |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set (0.00 sec)
```

If we choose filetype sql in your case:
`./bin/dumpling --filetype sql --escape-backslash=false`
```sql
/*!40101 SET NAMES binary*/;
INSERT INTO `t` VALUES
('''hello');
```

**Comment by kennytm** [comment]
The single quote should only be doubled if the quotation mark is also single quote.

* `'''hello'` ← correct way of escaping
* `"''hello"` ← **wrong** way of escaping.

CSV should only escape the double quotes, and leave the single quotes alone.
